#!/usr/bin/env gxi
;;; -*- Gerbil -*-
;;; Compile the parser-independent runtime and the bounded source-headline
;;; interface consumed by POO Flow Query. Generator tooling remains separate.

(import (only-in :std/build-script defbuild-script))

;; Gambit compiles generated C in GERBIL_PATH, not beside the source header.
;; The include search path is scoped to this build process and retains an
;; existing caller path (for example one supplied by Nix).
(let ((header-root (path-expand "bindings/c" (current-directory)))
      (previous (getenv "C_INCLUDE_PATH" #f)))
  (setenv "C_INCLUDE_PATH"
          (if (and previous (not (equal? previous "")))
            (string-append header-root ":" previous)
            header-root)))

(defbuild-script
 '((gxc: "languages/org/v1/modules/org-elements/graph-types.ss")
   (gxc: "languages/org/v1/modules/org-elements/graph-objects.ss")
   (gxc: "languages/org/v1/graph-shape.ss")
   (gxc: "languages/org/v1/modules/org-elements/types.ss")
   (gxc: "languages/org/v1/modules/org-elements/objects.ss")
   (gxc: "languages/org/v1/modules/org-elements/funs.ss")
   (gxc: "languages/org/v1/modules/org-elements/syntax.ss")
   (gxc: "languages/org/v1/modules/org-elements/runtime-interface.ss")
   (gxc: "languages/org/v1/modules/org-parser/types.ss")
   (gxc: "languages/org/v1/modules/org-parser/objects.ss")
   (gxc: "languages/org/v1/modules/org-parser/funs.ss")
   (gxc: "languages/org/v1/parser.ss")
   (gxc: "languages/org/v1/modules/org-parser/event-inline-primitives.ss")
   (gxc: "languages/org/v1/modules/org-parser/event-inline-link.ss")
   (gxc: "languages/org/v1/modules/org-parser/event-inline-url.ss")
   (gxc: "languages/org/v1/modules/org-parser/event-inline-citation-reference.ss")
   (gxc: "languages/org/v1/modules/org-parser/event-inline-citation.ss")
   (gxc: "languages/org/v1/modules/org-parser/event-inline-timestamp.ss")
   (gxc: "languages/org/v1/modules/org-parser/entity-names.ss")
   (gxc: "languages/org/v1/modules/org-parser/event-inline-entity.ss")
   (gxc: "languages/org/v1/modules/org-parser/event-inline-latex.ss")
   (gxc: "languages/org/v1/modules/org-parser/event-inline-script.ss")
   (gxc: "languages/org/v1/modules/org-parser/event-inline-cloze.ss")
   (gxc: "languages/org/v1/modules/org-parser/event-source-header.ss")
   (gxc: "languages/org/v1/modules/org-parser/event-inline.ss")
   (gxc: "languages/org/v1/modules/org-parser/event-paragraph.ss")
   (gxc: "languages/org/v1/modules/org-parser/event-headline-tags.ss")
   (gxc: "languages/org/v1/modules/org-parser/event-babel-call.ss")
   (gxc: "languages/org/v1/modules/org-parser/event-table-formula.ss")
   (gxc: "languages/org/v1/modules/org-parser/event-headline.ss")
   (gxc: "languages/org/v1/modules/org-parser/event-inlinetask.ss")
   (gxc: "languages/org/v1/modules/org-parser/event-include.ss")
   (gxc: "languages/org/v1/modules/org-parser/event-table.ss")
   (gxc: "languages/org/v1/modules/org-parser/event-tag-vocabulary.ss")
   (gxc: "languages/org/v1/modules/org-parser/event-list.ss")
   (gxc: "languages/org/v1/modules/org-parser/event-special-block.ss")
   (gxc: "languages/org/v1/modules/org-parser/event-latex-environment.ss")
   (gxc: "languages/org/v1/modules/org-parser/event-strategy.ss")
   (gxc: "languages/org/v1/grammar.ss")
   (gxc: "languages/org/v1/rowan-event-parser.ss")
   (gxc: "languages/org/v1/modules/org-elements/headline-properties.ss")
   (gxc: "languages/org/v1/modules/org-elements/source-headlines.ss")
   (gxc: "languages/org/v1/modules/org-elements/source-interface.ss")
   (gxc: "languages/org/v1/modules/org-contract/types.ss")
   (gxc: "languages/org/v1/modules/org-contract/objects.ss")
   (gxc: "languages/org/v1/modules/org-contract/funs.ss")
   (gxc: "languages/org/v1/modules/org-contract/config.ss")
   (gxc: "languages/org/v1/modules/org-contract/syntax.ss")
   (gxc: "languages/org/v1/modules/org-contract/runtime-interface.ss")
   (gxc: "bindings/c/orgize-native.ss")))
