use super::{
    workspace_contract_admits_exact_reciprocal_pair,
    workspace_contract_can_reject_reference_cycles, workspace_contract_can_reject_self_references,
    workspace_contract_checks_reciprocal_property_on_every_projection,
    workspace_contract_checks_target_property_on_every_projection,
    workspace_contract_compares_complete_target_property_values,
    workspace_contract_rejects_a_second_path_pattern_language,
    workspace_contract_rejects_an_invalid_route_contract_expression,
    workspace_contract_rejects_cross_group_counterparts,
    workspace_contract_rejects_duplicate_exact_contract_declarations,
    workspace_contract_rejects_duplicate_pair_group_declarations,
    workspace_contract_rejects_duplicate_reference_options,
    workspace_contract_rejects_inexact_contract_composition,
    workspace_contract_rejects_mismatched_paired_document_metadata_from_contract_expression,
    workspace_contract_rejects_mismatched_paired_node_identities,
    workspace_contract_rejects_mismatched_paired_node_metadata_from_contract_expression,
    workspace_contract_rejects_node_only_options_on_document_references,
    workspace_contract_rejects_nonreciprocal_and_escaping_counterparts,
    workspace_contract_rejects_third_semantic_projection,
    workspace_contract_rejects_unrouted_nested_org_file,
    workspace_contract_requires_allowed_properties_on_reference_targets,
    workspace_contract_requires_reciprocal_node_references,
    workspace_contract_resolves_document_property_values_to_node_identities,
    workspace_contract_resolves_node_property_values_and_allows_declared_sentinels,
};

pub(crate) const NATIVE_CASES: &[(&str, fn())] = &[
    (
        "contract_workspace::workspace_contract_admits_exact_reciprocal_pair",
        workspace_contract_admits_exact_reciprocal_pair,
    ),
    (
        "contract_workspace::workspace_contract_rejects_unrouted_nested_org_file",
        workspace_contract_rejects_unrouted_nested_org_file,
    ),
    (
        "contract_workspace::workspace_contract_rejects_a_second_path_pattern_language",
        workspace_contract_rejects_a_second_path_pattern_language,
    ),
    (
        "contract_workspace::workspace_contract_rejects_inexact_contract_composition",
        workspace_contract_rejects_inexact_contract_composition,
    ),
    (
        "contract_workspace::workspace_contract_rejects_nonreciprocal_and_escaping_counterparts",
        workspace_contract_rejects_nonreciprocal_and_escaping_counterparts,
    ),
    (
        "contract_workspace::workspace_contract_rejects_third_semantic_projection",
        workspace_contract_rejects_third_semantic_projection,
    ),
    (
        "contract_workspace::workspace_contract_rejects_mismatched_paired_node_identities",
        workspace_contract_rejects_mismatched_paired_node_identities,
    ),
    (
        "contract_workspace::workspace_contract_rejects_duplicate_pair_group_declarations",
        workspace_contract_rejects_duplicate_pair_group_declarations,
    ),
    (
        "contract_workspace::workspace_contract_rejects_cross_group_counterparts",
        workspace_contract_rejects_cross_group_counterparts,
    ),
    (
        "contract_workspace::workspace_contract_rejects_mismatched_paired_node_metadata_from_contract_expression",
        workspace_contract_rejects_mismatched_paired_node_metadata_from_contract_expression,
    ),
    (
        "contract_workspace::workspace_contract_rejects_mismatched_paired_document_metadata_from_contract_expression",
        workspace_contract_rejects_mismatched_paired_document_metadata_from_contract_expression,
    ),
    (
        "contract_workspace::workspace_contract_resolves_document_property_values_to_node_identities",
        workspace_contract_resolves_document_property_values_to_node_identities,
    ),
    (
        "contract_workspace::workspace_contract_resolves_node_property_values_and_allows_declared_sentinels",
        workspace_contract_resolves_node_property_values_and_allows_declared_sentinels,
    ),
    (
        "contract_workspace::workspace_contract_can_reject_self_references",
        workspace_contract_can_reject_self_references,
    ),
    (
        "contract_workspace::workspace_contract_can_reject_reference_cycles",
        workspace_contract_can_reject_reference_cycles,
    ),
    (
        "contract_workspace::workspace_contract_requires_reciprocal_node_references",
        workspace_contract_requires_reciprocal_node_references,
    ),
    (
        "contract_workspace::workspace_contract_requires_allowed_properties_on_reference_targets",
        workspace_contract_requires_allowed_properties_on_reference_targets,
    ),
    (
        "contract_workspace::workspace_contract_checks_target_property_on_every_projection",
        workspace_contract_checks_target_property_on_every_projection,
    ),
    (
        "contract_workspace::workspace_contract_compares_complete_target_property_values",
        workspace_contract_compares_complete_target_property_values,
    ),
    (
        "contract_workspace::workspace_contract_checks_reciprocal_property_on_every_projection",
        workspace_contract_checks_reciprocal_property_on_every_projection,
    ),
    (
        "contract_workspace::workspace_contract_rejects_an_invalid_route_contract_expression",
        workspace_contract_rejects_an_invalid_route_contract_expression,
    ),
    (
        "contract_workspace::workspace_contract_rejects_duplicate_exact_contract_declarations",
        workspace_contract_rejects_duplicate_exact_contract_declarations,
    ),
    (
        "contract_workspace::workspace_contract_rejects_node_only_options_on_document_references",
        workspace_contract_rejects_node_only_options_on_document_references,
    ),
    (
        "contract_workspace::workspace_contract_rejects_duplicate_reference_options",
        workspace_contract_rejects_duplicate_reference_options,
    ),
];
