use super::{
    clock_is_a_source_backed_element_between_paragraphs,
    closed_source_block_masks_heading_looking_body_lines,
    contract_scope_graph_projection_uses_only_scheme_owned_cst_rules,
    contract_scope_mvp_inputs_expose_drawers_and_node_properties,
    git_tracked_list_items_have_scheme_aot_ancestry_and_typed_bullets,
    git_tracked_org_document_is_lossless_at_the_current_structural_boundary,
    headings_form_nested_sections_and_closed_blocks_remain_lossless,
    incomplete_link_remains_lossless_text,
    invalid_property_drawer_recovers_without_claiming_node_properties,
    keyed_lines_obey_heading_context_and_project_keyword_fields,
    many_sibling_sections_keep_exact_source_order,
    recursive_greater_blocks_project_inner_elements_but_literal_blocks_do_not,
    scheme_aot_contract_evaluates_generated_org_element_ancestry,
    scheme_declared_babel_call_is_not_a_generic_keyword,
    scheme_declared_entities_require_catalog_names_and_preserve_postfix,
    scheme_declared_greater_blocks_keep_distinct_element_kinds_and_export_backend,
    scheme_declared_macro_objects_project_into_native_index_and_graph,
    scheme_declared_paragraphs_preserve_line_breaks_and_link_ancestry,
    scheme_declared_table_builds_rows_and_cells_without_paragraph_claims,
    scheme_emphasis_objects_project_into_native_index_and_element_graph,
    tracked_fixture_has_scheme_owned_keywords_and_planning,
    unclosed_source_block_recovers_as_text_before_the_next_headline,
    unmatched_greater_block_does_not_swallow_following_headline,
};

pub(crate) const NATIVE_CASES: &[(&str, fn())] = &[
    (
        "org_parser_aot::scheme_declared_macro_objects_project_into_native_index_and_graph",
        scheme_declared_macro_objects_project_into_native_index_and_graph,
    ),
    (
        "org_parser_aot::scheme_declared_entities_require_catalog_names_and_preserve_postfix",
        scheme_declared_entities_require_catalog_names_and_preserve_postfix,
    ),
    (
        "org_parser_aot::scheme_declared_babel_call_is_not_a_generic_keyword",
        scheme_declared_babel_call_is_not_a_generic_keyword,
    ),
    (
        "org_parser_aot::scheme_emphasis_objects_project_into_native_index_and_element_graph",
        scheme_emphasis_objects_project_into_native_index_and_element_graph,
    ),
    (
        "org_parser_aot::headings_form_nested_sections_and_closed_blocks_remain_lossless",
        headings_form_nested_sections_and_closed_blocks_remain_lossless,
    ),
    (
        "org_parser_aot::scheme_declared_paragraphs_preserve_line_breaks_and_link_ancestry",
        scheme_declared_paragraphs_preserve_line_breaks_and_link_ancestry,
    ),
    (
        "org_parser_aot::scheme_declared_table_builds_rows_and_cells_without_paragraph_claims",
        scheme_declared_table_builds_rows_and_cells_without_paragraph_claims,
    ),
    (
        "org_parser_aot::scheme_declared_greater_blocks_keep_distinct_element_kinds_and_export_backend",
        scheme_declared_greater_blocks_keep_distinct_element_kinds_and_export_backend,
    ),
    (
        "org_parser_aot::unmatched_greater_block_does_not_swallow_following_headline",
        unmatched_greater_block_does_not_swallow_following_headline,
    ),
    (
        "org_parser_aot::recursive_greater_blocks_project_inner_elements_but_literal_blocks_do_not",
        recursive_greater_blocks_project_inner_elements_but_literal_blocks_do_not,
    ),
    (
        "org_parser_aot::unclosed_source_block_recovers_as_text_before_the_next_headline",
        unclosed_source_block_recovers_as_text_before_the_next_headline,
    ),
    (
        "org_parser_aot::closed_source_block_masks_heading_looking_body_lines",
        closed_source_block_masks_heading_looking_body_lines,
    ),
    (
        "org_parser_aot::many_sibling_sections_keep_exact_source_order",
        many_sibling_sections_keep_exact_source_order,
    ),
    (
        "org_parser_aot::git_tracked_org_document_is_lossless_at_the_current_structural_boundary",
        git_tracked_org_document_is_lossless_at_the_current_structural_boundary,
    ),
    (
        "org_parser_aot::git_tracked_list_items_have_scheme_aot_ancestry_and_typed_bullets",
        git_tracked_list_items_have_scheme_aot_ancestry_and_typed_bullets,
    ),
    (
        "org_parser_aot::keyed_lines_obey_heading_context_and_project_keyword_fields",
        keyed_lines_obey_heading_context_and_project_keyword_fields,
    ),
    (
        "org_parser_aot::clock_is_a_source_backed_element_between_paragraphs",
        clock_is_a_source_backed_element_between_paragraphs,
    ),
    (
        "org_parser_aot::tracked_fixture_has_scheme_owned_keywords_and_planning",
        tracked_fixture_has_scheme_owned_keywords_and_planning,
    ),
    (
        "org_parser_aot::contract_scope_mvp_inputs_expose_drawers_and_node_properties",
        contract_scope_mvp_inputs_expose_drawers_and_node_properties,
    ),
    (
        "org_parser_aot::invalid_property_drawer_recovers_without_claiming_node_properties",
        invalid_property_drawer_recovers_without_claiming_node_properties,
    ),
    (
        "org_parser_aot::contract_scope_graph_projection_uses_only_scheme_owned_cst_rules",
        contract_scope_graph_projection_uses_only_scheme_owned_cst_rules,
    ),
    (
        "org_parser_aot::scheme_aot_contract_evaluates_generated_org_element_ancestry",
        scheme_aot_contract_evaluates_generated_org_element_ancestry,
    ),
    (
        "org_parser_aot::incomplete_link_remains_lossless_text",
        incomplete_link_remains_lossless_text,
    ),
];
