use super::{
    annotations_map_and_fold_work_across_the_tree,
    existing_html_traversal_still_uses_the_lossless_substrate,
    html_export_preserves_citation_raw_text,
    semantic_annotations_handle_parser_line_endings_and_utf8_columns,
    semantic_ast_covers_current_lossless_projection_surface,
    semantic_ast_keeps_affiliated_keywords_out_of_paragraph_objects,
    semantic_ast_keeps_quote_punctuation_plain, semantic_ast_projection_and_bare_snapshot,
    semantic_ast_projects_agenda, semantic_ast_projects_agenda_view_plan,
    semantic_ast_projects_agent_memory, semantic_ast_projects_agent_planning,
    semantic_ast_projects_attachments, semantic_ast_projects_babel_eval,
    semantic_ast_projects_block_code_refs, semantic_ast_projects_block_header_args,
    semantic_ast_projects_block_line_numbering, semantic_ast_projects_block_lines,
    semantic_ast_projects_citations, semantic_ast_projects_clean_clock_duration,
    semantic_ast_projects_clock_issues, semantic_ast_projects_clock_rollups,
    semantic_ast_projects_cloze_objects_with_metadata, semantic_ast_projects_column_views,
    semantic_ast_projects_crypt, semantic_ast_projects_dynamic_blocks,
    semantic_ast_projects_elements_bridge, semantic_ast_projects_file_todo_keywords,
    semantic_ast_projects_fixed_width_lines,
    semantic_ast_projects_footnote_definition_label_and_body, semantic_ast_projects_habits,
    semantic_ast_projects_include_dated_agenda_extras,
    semantic_ast_projects_inline_babel_and_footnote_details, semantic_ast_projects_inlinetasks,
    semantic_ast_projects_lesser_elements_and_blocks, semantic_ast_projects_lifecycle_archive,
    semantic_ast_projects_link_metadata, semantic_ast_projects_link_protocols,
    semantic_ast_projects_m15_alignment, semantic_ast_projects_m25_alignment,
    semantic_ast_projects_object_gap_repairs, semantic_ast_projects_org_interactive,
    semantic_ast_projects_org_table_formulas, semantic_ast_projects_preprocessing_directives,
    semantic_ast_projects_priority_properties, semantic_ast_projects_progress_stats,
    semantic_ast_projects_publishing, semantic_ast_projects_radio_links,
    semantic_ast_projects_refile, semantic_ast_projects_runtime_metadata,
    semantic_ast_projects_section_index_records, semantic_ast_projects_source_blocks,
    semantic_ast_projects_sparse_tree, semantic_ast_projects_table_column_metadata,
    semantic_ast_projects_table_el, semantic_ast_projects_table_visualization,
    semantic_ast_projects_tag_vocabulary, semantic_ast_projects_tangle_and_table_records,
    semantic_ast_projects_task_blockers, semantic_ast_projects_timestamp_metadata,
    semantic_ast_projects_workspace_index, semantic_ast_resolves_internal_links,
    semantic_citation_affixes_respect_parse_config, semantic_traversal_covers_parser_v2_surface,
    semantic_traversal_supports_exporter_and_indexer_shapes,
    traversal_visits_annotation_bearing_metadata_nodes,
};

pub(crate) fn cases() -> Vec<(&'static str, fn())> {
    let mut cases = Vec::new();
    for group in [
        annotations_map_and_fold_work_across_the_tree::NATIVE_CASES,
        existing_html_traversal_still_uses_the_lossless_substrate::NATIVE_CASES,
        html_export_preserves_citation_raw_text::NATIVE_CASES,
        semantic_annotations_handle_parser_line_endings_and_utf8_columns::NATIVE_CASES,
        semantic_ast_covers_current_lossless_projection_surface::NATIVE_CASES,
        semantic_ast_keeps_affiliated_keywords_out_of_paragraph_objects::NATIVE_CASES,
        semantic_ast_keeps_quote_punctuation_plain::NATIVE_CASES,
        semantic_ast_projection_and_bare_snapshot::NATIVE_CASES,
        semantic_ast_projects_agenda::NATIVE_CASES,
        semantic_ast_projects_agenda_view_plan::NATIVE_CASES,
        semantic_ast_projects_agent_memory::NATIVE_CASES,
        semantic_ast_projects_agent_planning::NATIVE_CASES,
        semantic_ast_projects_attachments::NATIVE_CASES,
        semantic_ast_projects_babel_eval::NATIVE_CASES,
        semantic_ast_projects_block_code_refs::NATIVE_CASES,
        semantic_ast_projects_block_header_args::NATIVE_CASES,
        semantic_ast_projects_block_line_numbering::NATIVE_CASES,
        semantic_ast_projects_block_lines::NATIVE_CASES,
        semantic_ast_projects_citations::NATIVE_CASES,
        semantic_ast_projects_clean_clock_duration::NATIVE_CASES,
        semantic_ast_projects_clock_issues::NATIVE_CASES,
        semantic_ast_projects_clock_rollups::NATIVE_CASES,
        semantic_ast_projects_cloze_objects_with_metadata::NATIVE_CASES,
        semantic_ast_projects_column_views::NATIVE_CASES,
        semantic_ast_projects_crypt::NATIVE_CASES,
        semantic_ast_projects_dynamic_blocks::NATIVE_CASES,
        semantic_ast_projects_file_todo_keywords::NATIVE_CASES,
        semantic_ast_projects_fixed_width_lines::NATIVE_CASES,
        semantic_ast_projects_footnote_definition_label_and_body::NATIVE_CASES,
        semantic_ast_projects_habits::NATIVE_CASES,
        semantic_ast_projects_include_dated_agenda_extras::NATIVE_CASES,
        semantic_ast_projects_inline_babel_and_footnote_details::NATIVE_CASES,
        semantic_ast_projects_inlinetasks::NATIVE_CASES,
        semantic_ast_projects_lesser_elements_and_blocks::NATIVE_CASES,
        semantic_ast_projects_lifecycle_archive::NATIVE_CASES,
        semantic_ast_projects_link_metadata::NATIVE_CASES,
        semantic_ast_projects_link_protocols::NATIVE_CASES,
        semantic_ast_projects_m15_alignment::NATIVE_CASES,
        semantic_ast_projects_m25_alignment::NATIVE_CASES,
        semantic_ast_projects_object_gap_repairs::NATIVE_CASES,
        semantic_ast_projects_org_interactive::NATIVE_CASES,
        semantic_ast_projects_org_table_formulas::NATIVE_CASES,
        semantic_ast_projects_preprocessing_directives::NATIVE_CASES,
        semantic_ast_projects_priority_properties::NATIVE_CASES,
        semantic_ast_projects_progress_stats::NATIVE_CASES,
        semantic_ast_projects_publishing::NATIVE_CASES,
        semantic_ast_projects_radio_links::NATIVE_CASES,
        semantic_ast_projects_refile::NATIVE_CASES,
        semantic_ast_projects_runtime_metadata::NATIVE_CASES,
        semantic_ast_projects_section_index_records::NATIVE_CASES,
        semantic_ast_projects_source_blocks::NATIVE_CASES,
        semantic_ast_projects_sparse_tree::NATIVE_CASES,
        semantic_ast_projects_table_column_metadata::NATIVE_CASES,
        semantic_ast_projects_table_el::NATIVE_CASES,
        semantic_ast_projects_table_visualization::NATIVE_CASES,
        semantic_ast_projects_tag_vocabulary::NATIVE_CASES,
        semantic_ast_projects_tangle_and_table_records::NATIVE_CASES,
        semantic_ast_projects_task_blockers::NATIVE_CASES,
        semantic_ast_projects_timestamp_metadata::NATIVE_CASES,
        semantic_ast_projects_workspace_index::NATIVE_CASES,
        semantic_ast_resolves_internal_links::NATIVE_CASES,
        semantic_citation_affixes_respect_parse_config::NATIVE_CASES,
        semantic_traversal_covers_parser_v2_surface::NATIVE_CASES,
        semantic_traversal_supports_exporter_and_indexer_shapes::NATIVE_CASES,
        traversal_visits_annotation_bearing_metadata_nodes::NATIVE_CASES,
    ] {
        cases.extend_from_slice(group);
    }
    cases.extend(semantic_ast_projects_elements_bridge::cases());
    cases
}
